name: graphblas
channels:
  - conda-forge
  - default
dependencies:
  - python=3.10
  - scipy
  - numba
  - matplotlib
  - networkx
  - pandas
  - rdkit
  - pip
  - llvm-openmp
  - pip:
    - python-graphblas