name: graphblas
channels:
  - rapidsai
  - conda-forge
  - nvidia
dependencies:
  - python=3.10
  - rapids=25.02
  - cuda-cudart
  - cuda-version=12
  - scipy
  - numba
  - matplotlib
  - networkx
  - pandas
  - rdkit
  - pip
  - pip:
    - python-graphblas
    - sparse